@file:Suppress("unused")

package com.cuso.tailor.di

import android.util.Log
import com.cuso.tailor.BuildConfig // Auto-generated by Gradle
import com.cuso.tailor.model.settings.WorkPricingCategory
import com.cuso.tailor.model.settings.WorkPricingCategoryDeserializer
import com.cuso.tailor.model.settings.WorkPricingGarment
import com.cuso.tailor.model.settings.WorkPricingGarmentDeserializer
import com.cuso.tailor.model.settings.WorkPricingSegment
import com.cuso.tailor.model.settings.WorkPricingSegmentDeserializer
import com.cuso.tailor.model.settings.WorkPricingTaxGroup
import com.cuso.tailor.model.settings.WorkPricingTaxGroupDeserializer
import com.cuso.tailor.network.SafeListTypeAdapterFactory
import com.cuso.tailor.network.auth.AuthApiService
import com.cuso.tailor.network.finance.FinanceApiService
import com.cuso.tailor.network.hr.HrApiService
import com.cuso.tailor.network.inventory.InventoryApiService
import com.cuso.tailor.network.inventory.settings.InventorySettingsApiService
import com.cuso.tailor.network.organization.OrganizationApiService
import com.cuso.tailor.network.sales.SalesCustomerApiService
import com.cuso.tailor.network.sales.SalesLeadApiService
import com.cuso.tailor.network.sales.SalesMeasurementsApiService
import com.cuso.tailor.network.sales.SalesOppertunitiesApiService
import com.cuso.tailor.network.sales.SalesOrderApiService
import com.cuso.tailor.network.sales.SalesPricingApiService
import com.cuso.tailor.network.sales.settings.SalesSettingsApiService
import com.cuso.tailor.network.user.UserApiService
import com.google.gson.Gson
import com.google.gson.GsonBuilder
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import okhttp3.OkHttpClient
import okhttp3.logging.HttpLoggingInterceptor
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory
import javax.inject.Singleton

@Module
@InstallIn(SingletonComponent::class)
object NetworkModule {

    // ---------------------------------------------------------
    // Base Network Infrastructure
    // ---------------------------------------------------------

    @Provides
    @Singleton
    fun provideLoggingInterceptor(): HttpLoggingInterceptor {
        return HttpLoggingInterceptor { message ->
            Log.d("OkHttp", message)
        }.apply {
            level = HttpLoggingInterceptor.Level.BODY
        }
    }

    @Provides
    @Singleton
    fun provideOkHttpClient(
        loggingInterceptor: HttpLoggingInterceptor
    ): OkHttpClient {
        return OkHttpClient.Builder()
            .addInterceptor(loggingInterceptor)
            .build()
    }

    @Provides
    @Singleton
    fun provideGson(): Gson {
        return GsonBuilder()
            .registerTypeAdapterFactory(SafeListTypeAdapterFactory())
            .registerTypeAdapter(WorkPricingSegment::class.java, WorkPricingSegmentDeserializer())
            .registerTypeAdapter(WorkPricingGarment::class.java, WorkPricingGarmentDeserializer())
            .registerTypeAdapter(WorkPricingCategory::class.java, WorkPricingCategoryDeserializer())
            .registerTypeAdapter(WorkPricingTaxGroup::class.java, WorkPricingTaxGroupDeserializer())
            .create()
    }

    @Provides
    @Singleton
    fun provideRetrofit(client: OkHttpClient, gson: Gson): Retrofit {
        return Retrofit.Builder()
            .baseUrl(BuildConfig.BASE_URL) // Automatically takes Localhost on Debug & Live on Release
            .client(client)
            .addConverterFactory(GsonConverterFactory.create(gson))
            .build()
    }

    // ---------------------------------------------------------
    // Modular API Service Providers
    // ---------------------------------------------------------

    @Provides
    @Singleton
    fun provideAuthApiService(retrofit: Retrofit): AuthApiService =
        retrofit.create(AuthApiService::class.java)

    @Provides
    @Singleton
    fun provideUserApiService(retrofit: Retrofit): UserApiService =
        retrofit.create(UserApiService::class.java)

    @Provides
    @Singleton
    fun provideOrganizationApiService(retrofit: Retrofit): OrganizationApiService =
        retrofit.create(OrganizationApiService::class.java)

    @Provides
    @Singleton
    fun provideSalesLeadApiService(retrofit: Retrofit): SalesLeadApiService =
        retrofit.create(SalesLeadApiService::class.java)

    @Provides
    @Singleton
    fun provideSalesOrderApiService(retrofit: Retrofit): SalesOrderApiService =
        retrofit.create(SalesOrderApiService::class.java)

    @Provides
    @Singleton
    fun provideSalesCustomerApiService(retrofit: Retrofit): SalesCustomerApiService =
        retrofit.create(SalesCustomerApiService::class.java)

    @Provides
    @Singleton
    fun provideSalesPricingApiService(retrofit: Retrofit): SalesPricingApiService =
        retrofit.create(SalesPricingApiService::class.java)

    @Provides
    @Singleton
    fun provideSalesMeasurementsApiService(retrofit: Retrofit): SalesMeasurementsApiService =
        retrofit.create(SalesMeasurementsApiService::class.java)

    @Provides
    @Singleton
    fun provideSalesOppertunitiesApiService(retrofit: Retrofit): SalesOppertunitiesApiService =
        retrofit.create(SalesOppertunitiesApiService::class.java)

    @Provides
    @Singleton
    fun provideFinanceApiService(retrofit: Retrofit): FinanceApiService =
        retrofit.create(FinanceApiService::class.java)

    @Provides
    @Singleton
    fun provideInventoryApiService(retrofit: Retrofit): InventoryApiService =
        retrofit.create(InventoryApiService::class.java)

    @Provides
    @Singleton
    fun provideHrApiService(retrofit: Retrofit): HrApiService =
        retrofit.create(HrApiService::class.java)

    @Provides
    @Singleton
    fun provideSettingsApiService(retrofit: Retrofit): SalesSettingsApiService {
        return retrofit.create(SalesSettingsApiService::class.java)
    }

    @Provides
    @Singleton
    fun provideInventorySettingsApiService(retrofit: Retrofit): InventorySettingsApiService {
        return retrofit.create(InventorySettingsApiService::class.java)
    }
}